import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
});

export const metadata: Metadata = {
    title: "Create Next App | Custom Title",
    description: "Generated by create next app",
    openGraph: {
        title: "Create Next App",
        description: "A custom app created with Next.js",
        url: "https://your-app-url.com",
        siteName: "Create Next App",
        images: [
            {
                url: "/og-image.png",
                width: 800,
                height: 600,
                alt: "Open Graph Image",
            },
        ],
    },
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
    <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
            {children}
        </body>
    </html>
);

export default RootLayout;
